name: 'pr-lint-jira'
description: 'Lint PR to ensure a JIRA ticket is found in both the title and the body'

inputs:
  token:
    description: 'GitHub authentication token'
    required: true
  make_pr_comment:
    description: if enabled, create a PR comment on missing JIRA ticket
    required: false
    default: 'false'
  title_regex:
    description: regex that matches JIRA ticket in PR title. defaults to starting with JIRA ticket in square brackets.
    required: false
    default: '^\[([A-Z]{2,})(-)(\d+)\]'
  body_regex:
    description: regex that matches JIRA ticket in PR body. defaults to JIRA ticket in square brackets being anywhere in PR body
    required: false
    default: '\[([A-Z]{2,})(-)(\d+)\]'
  no_ticket:
    description: 'your PR has no associated JIRA ticket. use this string in both the PR title and body to pass linting'
    required: false
    default: '[no-ticket]'

runs:
  using: 'node12'
  main: 'dist/index.js'

branding:
  icon: 'git-pull-request'
  color: 'blue'
