name: "drmaples/pr-lint-jira"
description: "Lint PR to ensure a ticket is found in both the title and the body"

inputs:
  token:
    description: "GitHub authentication token"
    required: true
  make_pr_comment:
    description: if enabled, create a PR comment on missing ticket
    required: false
    default: "false"
  title_regex:
    description: regex that matches ticket in PR title. defaults to ticket in square brackets anywhere in the title. see source code for default value
    required: false
  body_regex:
    description: regex that matches ticket in PR body. defaults to ticket in square brackets being anywhere in PR body. see source code for default value
    required: false
  no_ticket:
    description: your PR has no associated ticket. use this string in both the PR title and body to pass linting. see source code for default value
    required: false

runs:
  using: "docker"
  # switch this to a pre-built ghcr image
  image: "Dockerfile"

branding:
  icon: "git-pull-request"
  color: "blue"
